import {ReactNode} from "react";
import './styles/globals.css'
import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import Header from "@/widgets/Header";
import Footer from "@/widgets/Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({children}: Readonly<{children: ReactNode}>) => {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <Header/>
                {children}
                <Footer/>
            </body>
        </html>
    );
};

export default RootLayout;